apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quizloom-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  namespace: quizloom
spec:
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: quizloom-backend-service
                port:
                  number: 5000
