apiVersion: v1
kind: Service
metadata:
  name: quizloom-database-service
  namespace: quizloom

spec:
  clusterIP: None
  selector:
    app: quizloom-database
  ports:
    - name: quizloom-database
      protocol: TCP
      port: 5432
      targetPort: 5432
