name: GitHub Actions QuizLoom
run-name: ${{ github.actor }} is running Quizloom GitHub Actions 🚀

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "23"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run ESLint
        run: pnpm lint

      - name: Run Prettier for Code Formatting
        run: pnpm format

      - name: Run Dependency Check (OWASP Dependency-Check)
        uses: dependency-check/Dependency-Check_Action@1.1.0
        id: dependencyCheck
        with:
          project: "QuizLoom"
          path: "."
          format: "ALL"

      - name: Build the Application
        run: pnpm build

  deploy:
    name: Deploy to Docker
    needs: build-setup
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKERIMAGE_NAME: ${{ secrets.DOCKERIMAGE_NAME }}
      DOCKERIMAGE_TAG: build-${{ github.run_number }}
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
      - name: Build Docker Image
        run: docker build -t ${{ env.DOCKERIMAGE_NAME }}:${{ env.DOCKERIMAGE_TAG }} --platform linux/amd64 -f docker/production/Dockerfile .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: "${{ env.DOCKERIMAGE_NAME }}:${{ env.DOCKERIMAGE_TAG }}"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
      
      - name: Push to DockerHub
        run: docker push ${{ env.DOCKERIMAGE_NAME }}:${{ env.DOCKERIMAGE_TAG }}
      
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
          wait-for-success: true
