name: GitHub Actions QuizLoom
run-name: ${{ github.actor }} is running Quizloom GitHub Actions 🚀

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run Prettier for Code Formatting
        run: npm run format

      # - name: Run Unit Tests And Collect Test Coverage (using Jest)
      #   run: npm test

      # - name: Upload Coverage to Coveralls
      #   uses: coverallsapp/github-action@v2
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Dependency Check (OWASP Dependency-Check)
        uses: dependency-check/Dependency-Check_Action@1.1.0
        id: dependencyCheck
        with:
          project: "QuizLoom"
          path: "."
          format: "ALL"

      - name: Build the Application
        run: npm run build
